CREATE TABLE contenido (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo VARCHAR2(150) NOT NULL,
    texto CLOB NOT NULL,
    categoria VARCHAR2(100) NOT NULL,
    probabilidad NUMBER(5,4) NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    usuario_id NUMBER,

    CONSTRAINT pk_contenido
        PRIMARY KEY (id),

    CONSTRAINT fk_contenido_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES users(id)
);

CREATE INDEX idx_contenido_usuario
ON contenido(usuario_id);

CREATE INDEX idx_contenido_categoria
ON contenido(categoria);
