spring.application.name=backend

server.port=8080

#      BASE DE DATOS H2
# URL de conexión a la base de datos en memoria
spring.datasource.url=jdbc:h2:mem:authdb

# Usuario por defecto de H2
spring.datasource.username=sa

# Contraseña del usuario (vacía por defecto)
spring.datasource.password=

# Driver JDBC utilizado por H2
spring.datasource.driver-class-name=org.h2.Driver

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Formatear el SQL para facilitar su lectura
spring.jpa.properties.hibernate.format_sql=true

# Validar que las tablas existan (Flyway será quien las cree)
spring.jpa.hibernate.ddl-auto=validate

# Habilita las migraciones automáticas Flyway
spring.flyway.enabled=true

# Permite acceder a la consola web de H2
spring.h2.console.enabled=true

# Desactiva Open Session in View (buena práctica)
spring.jpa.open-in-view=false

# Secreto JWT: usa la variable JWT_SECRET si existe, de lo contrario usa "hackathon" para pruebas locales
jwt.secret=${JWT_SECRET:hackathon}

# +++++++LINK PRUEBA DE DB H2******************
#podrás conectarte a la base de datoS http://localhost:8080/h2-console
# USER = sa
# password = dejar vacio